[advisories]
ignore = []

[licenses]
allow = [
  "MIT",
  "Apache-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "ISC",
  "Unicode-3.0",
  "Unicode-DFS-2016",
  "OpenSSL",
  "Zlib",
  "BSL-1.0",
  "CC0-1.0",
  "MPL-2.0",
]

[[licenses.exceptions]]
allow = ["GPL-3.0"]
crate = "driller"

[bans]
multiple-versions = "warn"
wildcards = "allow"

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
